apiVersion: microcks.io/v1alpha1
kind: APISource
metadata:
  name: tests-artifacts
  annotations:
    microcks.io/instance: microcks
spec:
  artifacts:
    - url: https://raw.githubusercontent.com/vmarzal/microcks/refs/heads/main/samples/hci_openapi_complete.yaml
      mainArtifact: true
    - url: https://raw.githubusercontent.com/vmarzal/microcks/refs/heads/main/samples/leire.soapui.xml
      mainArtifact: true
