apiVersion: microcks.io/v1alpha1
kind: APISource
metadata:
  name: tests-artifacts
  annotations:
    microcks.io/instance: microcks
spec:
  artifacts:
    - url: https://raw.githubusercontent.com/vmarzal/microcks/main/samples/hci.openapi.yaml
      mainArtifact: true
    - url: https://raw.githubusercontent.com/vmarzal/microcks/main/samples/leire.soapui.xml
      mainArtifact: true
    - url: https://raw.githubusercontent.com/vmarzal/microcks/main/samples/nextflow.openapi.yaml
      mainArtifact: true
